// SPDX-License-Identifier: GPL-3.0-or-later
#pragma once

#include "render/TerrainManifest.h"

#include <cstdint>
#include <span>

namespace fl {

// Minimal glTF 2.0 binary (.glb) meshes embedded as byte arrays.
// Generated by tools/gen_builtin_glb.py; uploaded via IRenderer::createMesh.
//
// kTetrahedronGlb — regular tetrahedron, ~20 m circumradius, +X forward.
//   4 triangular faces, 12 vertices with per-face normals (POSITION + NORMAL).
//   Used as a placeholder mesh for entities when no content pack provides one.
//
// kFloorPlaneGlb — flat 4 km × 4 km quad at Y=0, normal (0,1,0).
//   4 vertices, 6 indices. Used as the builtin sandbox floor plane.

std::span<const uint8_t> builtinTetrahedronGlb() noexcept;
std::span<const uint8_t> builtinFloorPlaneGlb() noexcept;

// Individual faces of the tetrahedron — one triangle each, for per-face coloring.
// face 0: red   face 1: green   face 2: blue   face 3: yellow
std::span<const uint8_t> builtinTetrahedronFaceGlb(int face) noexcept; // face in [0,3]

// TerrainManifest for the builtin procedural world: the cube-sphere quadtree
// ("world", maxTileLevel 12 — ~30 m per mesh quad on Earth). Procedural tiles
// cover any TileKey, so the world is globally unbounded (#472).
TerrainManifest builtinWorldTerrainManifest() noexcept;

} // namespace fl
