// SPDX-License-Identifier: GPL-3.0-or-later
#pragma once

#include "render/BuiltinShape.h"
#include "render/TerrainManifest.h"

#include <cstdint>
#include <span>

namespace fl {

// Minimal glTF 2.0 binary (.glb) meshes embedded as byte arrays.
// Generated by tools/gen_builtin_glb.py; uploaded via IRenderer::createMesh.
//
// kFloorPlaneGlb — flat 4 km × 4 km quad at Y=0, normal (0,1,0).
//   4 vertices, 6 indices. Used as the builtin sandbox floor plane.

std::span<const uint8_t> builtinFloorPlaneGlb() noexcept;

// Per-category placeholder silhouettes (#886), keyed by BuiltinShape. Every span is a valid
// single-primitive .glb; an out-of-range ordinal returns the Unknown error beacon. The damaged
// variant is a slumped wreck for the persistent categories (aircraft / ground vehicle / naval
// vessel / structure); shapes without a wreck (projectiles despawn on death, Unknown is a bug
// marker) return their intact span, so callers never branch on "has wreck". These replaced the
// single legacy debug wedge (builtinTetrahedronGlb) — every category now has a real silhouette
// and the Unknown beacon renders only in bug states.
std::span<const uint8_t> builtinShapeGlb(BuiltinShape shape) noexcept;
std::span<const uint8_t> builtinDamagedShapeGlb(BuiltinShape shape) noexcept;

// TerrainManifest for the builtin procedural world: the cube-sphere quadtree
// ("world", maxTileLevel 12 — ~30 m per mesh quad on Earth). Procedural tiles
// cover any TileKey, so the world is globally unbounded (#472).
TerrainManifest builtinWorldTerrainManifest() noexcept;

} // namespace fl
