#!/usr/bin/env bash
# Tags main with vX.Y.Z and pushes to trigger the release workflow.
# Run after the release PR (created by cut-release.sh) is merged.
#
# The tag is NOT the last step. See docs/project-management.md, "Cutting a release" — the
# hand-authored release notes come after the workflow finishes, and they are the step that has
# been skipped most often.
set -euo pipefail

VERSION="${1:?Usage: $0 vMAJOR.MINOR.PATCH}"

if [[ ! "$VERSION" =~ ^v[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
    echo "Error: version must be in vMAJOR.MINOR.PATCH format" >&2
    exit 1
fi

BRANCH=$(git rev-parse --abbrev-ref HEAD)
if [[ "$BRANCH" != "main" ]]; then
    echo "Error: must be on main (currently on '$BRANCH')" >&2
    exit 1
fi

git pull origin main

SEMVER="${VERSION#v}"
TODAY=$(date +%F)

# The CHANGELOG's section date must be the date the tag is created — that is the date the release
# actually came out, it is what fires release.yml, and it is what the GitHub Release body states.
# cut-release.sh stamps the day the release PR was authored, so a PR that sits overnight drifts.
# [0.2.0] and [0.3.3] both shipped a day out this way before anyone noticed.
CL_DATE=$(sed -n "s/^## \[${SEMVER}\] - \([0-9-]*\)$/\1/p" CHANGELOG.md | head -1)

if [[ -z "$CL_DATE" ]]; then
    echo "Error: CHANGELOG.md has no '## [$SEMVER] - YYYY-MM-DD' section." >&2
    echo "       Did the release PR merge? Run cut-release.sh first." >&2
    exit 1
fi

if [[ "$CL_DATE" != "$TODAY" ]]; then
    echo "Error: CHANGELOG.md dates [$SEMVER] as $CL_DATE, but the tag would be created $TODAY." >&2
    echo "       Fix the heading to '## [$SEMVER] - $TODAY' and merge that before tagging," >&2
    echo "       so the changelog, the tag and the release body all agree." >&2
    exit 1
fi

git tag -a "$VERSION" -m "$VERSION"
git push origin "$VERSION"

cat <<EOF

Tag $VERSION pushed. Release workflow:
  https://github.com/fighters-legacy/fighters-legacy/actions/workflows/release.yml

THE RELEASE IS NOT DONE. Remaining steps (docs/project-management.md, "Cutting a release"):

  1. WAIT for the Release workflow to COMPLETE. Its softprops/action-gh-release step SETS the
     release body to git-cliff's collapsed list, so notes applied before it finishes are
     overwritten. This is how v0.3.8 lost its hand-authored body.

  2. Verify the archives actually attached — a green workflow is not evidence:
       gh release view $VERSION --json assets -q '.assets[] | "\(.name) \(.size)"'
     Expect fighters-legacy-{linux,macos,windows}.zip.

  3. Write the notes and apply them to THIS tag:
       gh release edit $VERSION --notes-file <file>

  4. Read the body back and confirm it is the right release:
       gh release view $VERSION --json body -q '.body' | head -3
     v0.3.9's notes were once applied to v0.3.8, and v0.2.5's to v0.2.6 — both clobbered a
     previous release and went unnoticed for months. The read-back is what catches that.

The release-notes gate (.github/workflows/release-notes-gate.yml) checks 1-4 automatically and
opens a tracking issue if the body is autogenerated or describes the wrong version.
EOF
